begin;

create table if not exists public.leaderboard_score_log (
  id bigint generated by default as identity primary key,
  player_id uuid not null,
  player_name varchar(16) not null,
  difficulty text not null check (difficulty in ('easy', 'medium', 'hard', 'alin')),
  submitted_floor integer not null check (submitted_floor between 1 and 1000000),
  submitted_next_floor integer check (submitted_next_floor between 1 and 1000000),
  previous_floor integer,
  resulting_floor integer not null,
  score integer not null check (score >= 0),
  elapsed_seconds integer not null check (elapsed_seconds >= 0),
  mistakes integer not null check (mistakes >= 0),
  stars smallint not null check (stars between 1 and 3),
  accepted boolean not null,
  decision text not null check (decision in ('new_row', 'higher_floor', 'better_score_same_floor', 'not_higher')),
  app_version varchar(20) not null default '',
  created_at timestamptz not null default now()
);

create index if not exists leaderboard_score_log_player_created_idx
  on public.leaderboard_score_log (player_id, created_at desc);
create index if not exists leaderboard_score_log_player_difficulty_idx
  on public.leaderboard_score_log (player_id, difficulty, created_at desc);

alter table public.leaderboard_score_log enable row level security;
revoke all on public.leaderboard_score_log from anon, authenticated;

drop function if exists public.submit_leaderboard_score(uuid, text, text, integer, integer, integer, integer, integer);
drop function if exists public.submit_leaderboard_score(uuid, text, text, integer, integer, integer, integer, integer, text, integer);
drop function if exists public.submit_leaderboard_score(uuid, text, text, integer, integer, integer, integer, integer, text, integer, text);
drop function if exists public.submit_leaderboard_score(uuid, text, text, integer, integer, integer, integer, integer, text, integer, text, integer, text);

create function public.submit_leaderboard_score(
  p_player_id uuid,
  p_player_name text,
  p_difficulty text,
  p_floor integer,
  p_score integer,
  p_elapsed_seconds integer,
  p_mistakes integer,
  p_stars integer,
  p_player_avatar text,
  p_avatar_color integer,
  p_pin text,
  p_next_floor integer default null,
  p_app_version text default ''
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_previous_floor integer;
  v_previous_score integer;
  v_resulting_floor integer;
  v_accepted boolean;
  v_decision text;
begin
  if char_length(trim(p_player_name)) not between 1 and 16
    or p_difficulty not in ('easy', 'medium', 'hard', 'alin')
    or p_floor not between 1 and 1000000
    or (p_next_floor is not null and p_next_floor not between 1 and 1000000)
    or p_score < 0
    or p_elapsed_seconds < 0
    or p_mistakes < 0
    or p_stars not between 1 and 3
    or (p_player_avatar is not null and (char_length(p_player_avatar) > 32 or p_player_avatar !~ '^[a-z_]+$'))
    or coalesce(p_avatar_color, 0) not between 0 and 7
    or char_length(coalesce(p_app_version, '')) > 20
    or p_pin is null
    or p_pin !~ '^\d{4}$' then
    raise exception 'Invalid leaderboard score';
  end if;

  if not exists (
    select 1
    from public.cloud_saves
    where player_id = p_player_id
      and pin_hash = extensions.crypt(p_pin, pin_hash)
  ) then
    raise exception 'Invalid cloud PIN';
  end if;

  select floor, score
  into v_previous_floor, v_previous_score
  from public.leaderboard_scores
  where player_id = p_player_id
    and difficulty = p_difficulty
  for update;

  v_accepted := v_previous_floor is null
    or p_floor > v_previous_floor
    or (p_floor = v_previous_floor and p_score > v_previous_score);
  v_decision := case
    when v_previous_floor is null then 'new_row'
    when p_floor > v_previous_floor then 'higher_floor'
    when p_floor = v_previous_floor and p_score > v_previous_score then 'better_score_same_floor'
    else 'not_higher'
  end;

  insert into public.leaderboard_scores (
    player_id, player_name, difficulty, floor, score, elapsed_seconds, mistakes, stars, player_avatar, avatar_color
  ) values (
    p_player_id, trim(p_player_name), p_difficulty, p_floor, p_score, p_elapsed_seconds, p_mistakes, p_stars, p_player_avatar, coalesce(p_avatar_color, 0)
  )
  on conflict (player_id, difficulty) do update set
    player_name = excluded.player_name,
    floor = excluded.floor,
    score = excluded.score,
    elapsed_seconds = excluded.elapsed_seconds,
    mistakes = excluded.mistakes,
    stars = excluded.stars,
    player_avatar = excluded.player_avatar,
    avatar_color = excluded.avatar_color,
    updated_at = now()
  where excluded.floor > public.leaderboard_scores.floor
     or (excluded.floor = public.leaderboard_scores.floor and excluded.score > public.leaderboard_scores.score);

  select floor
  into v_resulting_floor
  from public.leaderboard_scores
  where player_id = p_player_id
    and difficulty = p_difficulty;

  insert into public.leaderboard_score_log (
    player_id, player_name, difficulty, submitted_floor, submitted_next_floor,
    previous_floor, resulting_floor, score, elapsed_seconds, mistakes, stars,
    accepted, decision, app_version
  ) values (
    p_player_id, trim(p_player_name), p_difficulty, p_floor, p_next_floor,
    v_previous_floor, v_resulting_floor, p_score, p_elapsed_seconds, p_mistakes, p_stars,
    v_accepted, v_decision, coalesce(p_app_version, '')
  );

  -- Bound free-tier growth while retaining a long per-mode diagnostic trail.
  delete from public.leaderboard_score_log
  where id in (
    select old_log.id
    from public.leaderboard_score_log as old_log
    where old_log.player_id = p_player_id
      and old_log.difficulty = p_difficulty
    order by old_log.created_at desc, old_log.id desc
    offset 500
  );
end;
$$;

revoke all on function public.submit_leaderboard_score(uuid, text, text, integer, integer, integer, integer, integer, text, integer, text, integer, text) from public;
grant execute on function public.submit_leaderboard_score(uuid, text, text, integer, integer, integer, integer, integer, text, integer, text, integer, text) to anon, authenticated;

create or replace function public.get_leaderboard_score_log(
  p_player_id uuid,
  p_pin text,
  p_limit integer default 100
)
returns table (
  id bigint,
  difficulty text,
  submitted_floor integer,
  submitted_next_floor integer,
  previous_floor integer,
  resulting_floor integer,
  score integer,
  elapsed_seconds integer,
  mistakes integer,
  stars smallint,
  accepted boolean,
  decision text,
  app_version varchar(20),
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_pin is null
    or p_pin !~ '^\d{4}$'
    or p_limit not between 1 and 500
    or not exists (
      select 1
      from public.cloud_saves
      where player_id = p_player_id
        and pin_hash = extensions.crypt(p_pin, pin_hash)
    ) then
    raise exception 'Invalid cloud PIN';
  end if;

  return query
  select
    log.id,
    log.difficulty,
    log.submitted_floor,
    log.submitted_next_floor,
    log.previous_floor,
    log.resulting_floor,
    log.score,
    log.elapsed_seconds,
    log.mistakes,
    log.stars,
    log.accepted,
    log.decision,
    log.app_version,
    log.created_at
  from public.leaderboard_score_log as log
  where log.player_id = p_player_id
  order by log.created_at desc
  limit p_limit;
end;
$$;

revoke all on function public.get_leaderboard_score_log(uuid, text, integer) from public;
grant execute on function public.get_leaderboard_score_log(uuid, text, integer) to anon, authenticated;

commit;
